"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_1 = require("../controllers/user");
const route = (0, express_1.Router)();
route.get("/details/:userId", user_1.getUser);
route.post('/register', user_1.register);
route.post('/login', user_1.login);
route.post('/logout', user_1.logout);
route.put('/edit/:userId', user_1.edit);
route.delete('/delete/:userId', user_1.deleteUser);
exports.default = route;
